config/routes.rb
Dashboard::Application.routes.draw do
  resources :teacher_bonus_prizes
  resources :teacher_prizes
  resources :prizes
  resources :callouts
  resources :videos
  resources :concepts
  resources :activities
  resources :sections, only: [:new, :create, :edit, :update, :destroy]
  resources :level_sources, path: '/sh/', only: [:show, :edit]
  get '/share/:id', to: redirect('/sh/%{id}')
  get '/sh/:id/generate_image', to: 'level_sources#generate_image'

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    sessions: 'sessions'
  }

  post '/signup_check/username', to: 'home#check_username'

  root :to => "home#index"
  get '/home_insert', to: 'home#home_insert'
  get '/health_check', to: 'home#health_check'
  get '/admin/debug', to: 'home#debug'

  post '/locale', to: 'home#set_locale', as: 'locale'

  resources :games do
    resources :levels
  end

  resources :scripts, only: [], path: '/s/' do
    resources :script_levels, as: :levels, only: [:show], path: "/level", format: false do
      get 'solution', to: 'script_levels#solution'
    end
  end

  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID, reset:true, as: 'hoc_reset'
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID, as: 'hoc_chapter', format: false

  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID, as: 'k8intro_chapter', format: false

  resources :prize_providers
  get '/prize_providers/:id/claim_prize', to: 'prize_providers#claim_prize', as: 'prize_provider_claim_prize'

  resources :followers, only: [:new, :create, :index]
  get '/followers/:teacher_user_id/accept', to: 'followers#accept', as: 'follower_accept'
  post '/followers/create_student', to: 'followers#create_student', as: 'create_student'
  get '/followers/manage', to: 'followers#manage', as: 'manage_followers'

  get '/followers/change_password/:user_id', to: 'followers#student_edit_password', as: 'student_edit_password'
  post '/followers/save_password', to: 'followers#student_update_password', as: 'student_update_password'

  post '/followers/add_to_section', to: 'followers#add_to_section', as: 'add_to_section'
  post '/followers/remove_from_section', to: 'followers#remove_from_section', as: 'remove_from_section'
  get '/join(/:section_code)', to: 'followers#student_user_new', as: 'student_user_new'
  post '/join/:section_code', to: 'followers#student_register', as: 'student_register'

  post '/milestone/:user_id/:script_level_id', :to => 'activities#milestone', :as => 'milestone'

  get '/admin/usage', to: 'reports#all_usage', as: 'all_usage'
  get '/admin/stats', to: 'reports#admin_stats', as: 'admin_stats'
  get '/admin/progress', to: 'reports#admin_progress', as: 'admin_progress'
  get '/stats/usage/:user_id', to: 'reports#usage', as: 'usage'
  get '/stats/students', to: 'reports#students', as: 'student_usage'
  get '/stats/:user_id', to: 'reports#user_stats', as: 'user_stats'
  get '/stats/level/:level_id', to: 'reports#level_stats', as: 'level_stats'
  get '/popup/stats', to: 'reports#header_stats', as: 'header_stats'
  get '/redeemprizes', to: 'reports#prizes', as: 'my_prizes'

  get '/notes/:key', to: 'notes#index'

  get '/api/user_menu', to: 'api#user_menu', as: 'user_menu'
  get '/api/user_hero', to: 'api#user_hero', as: 'user_hero'

end

app/views/shared/_choose_prize.html.haml
- found_provider = false
- PrizeProvider.all.each do |provider|
  - if prize_collection.where(:prize_provider_id => provider.id).where(:user_id => nil).count > 0
    - found_provider = true
    .prize-item-grid
      %p
        - confirm_msg = '<h4>' + t('redeem_prizes.confirm.msg', prize_name: t('redeem_prizes.providers.' + provider.description_token)) + '</h4>'
        - confirm_msg += (t('redeem_prizes.confirm.msg_student') + '<br><br>') if (prize_type === 'student')
        - confirm_msg += '<a target="_blank" href="' + provider.url + '">' + t('redeem_prizes.confirm.msg_visit_website') + '</a>'
        - confirm_msg += '<br><br><div class="prize-confirm-redemption">' + Dashboard::Application::config.prize_providers[provider.description_token]['redemption'] + '</div>'
        - confirm_msg += ('<br><label><input class="prize-chk" type="checkbox">' + t('redeem_prizes.confirm.msg_publicschool') + '</label>') if (prize_type === 'teacher')
        - confirm_msg += '<script>$("#dataConfirmOK").attr("disabled", true);$("#dataConfirmOK").click(function(e){ if($(this).attr("disabled")) {e.preventDefault();} });$(".prize-chk").click(function(){ $("#dataConfirmOK").attr("disabled", !this.checked); });</script>' if (prize_type === 'teacher')
        = link_to prize_provider_claim_prize_path(provider.id, :type => prize_type), :confirm => confirm_msg do
          = image_tag(provider.image_name, :class => 'prize-card-img')
          = t('redeem_prizes.providers.' + provider.description_token)
- if !found_provider
  %br/
  %br/
  = t('redeem_prizes.no_prizes_available')
  %br/
  %br/

app/views/shared/_concept_trophy_block.html.haml
%div{style:"display:inline-block;width:290px;position:relative;overflow:hidden;float:left;" + added_style}
  %h4 #{t('nav.popup.mastery')}

  %table{style:"max-width:290px;"}
    - if concept_progress
      - concept_progress.each_pair do |concept, counts|
      - completion = counts[:current].to_f/counts[:max]
        =render partial: 'shared/concept_trophy_row', locals: { concept: concept, completion: completion }
        <!-- #{counts} -->
    - else
      - Concept.cached.each do |concept|
        =render partial: 'shared/concept_trophy_row', locals: { concept: concept, completion: 0 }
  - if current_user && user == current_user && current_user.show_prize_ui?
    .stage_separator
    .prize-msg
      - if current_user.prize_earned
        #{t('nav.popup.prize_earned', total_trophies: concept_progress.length * Trophy::TROPHIES_PER_CONCEPT)}
      - elsif
        #{t('nav.popup.prizes', total_trophies: concept_progress.length * Trophy::TROPHIES_PER_CONCEPT)}
      <br>
      #{t('nav.popup.prize_us_only')} #{link_to t('nav.popup.prizes_link'), my_prizes_path}

app/views/shared/_concept_trophy_row.html.haml
%tr{ height:"55px"}
  %td{width:"100px"}
    #{data_t('concept.description', concept.name)}:
  %td{width:"55px", style:"text-align:center;"}
    = image_tag bronze_fraction_image_path(completion), class: "trophy_image"
  %td{width:"55px", style:"text-align:center;"}
    = image_tag silver_fraction_image_path(completion), class: "trophy_image"
  %td{width:"55px", style:"text-align:center;"}
    = image_tag gold_fraction_image_path(completion), class: "trophy_image"

app/views/shared/_redeemed_prize.html.haml
- provider = prize.prize_provider
= image_tag provider.image_name, :class => 'prize-card-img'
%p
  %b= t('redeem_prizes.provider')
  = link_to(t('redeem_prizes.providers.' + provider.description_token), provider.url)
%p
  %b= t('redeem_prizes.code')
  %span{class: 'prize-code'} #{prize.code}
%p
  %span{class: 'prize-redemption'} #{Dashboard::Application::config.prize_providers[provider.description_token]['redemption']}

app/views/shared/_script_levels.html.haml
- if script
  - script_levels = user ? user.levels_from_script(script) : script.script_levels

  %div
    - script_levels.each do |sl|
      - link = build_script_level_path(sl)
      - best_result = sl.user_level ? sl.user_level.best_result : nil
      = link_to ' ', link, class: "#{"level_current " if sl.level_id == level.try(:id)}level_box #{level_box_class(best_result)}"

app/views/shared/_solution.html.haml
%div{ style: 'position:relative;height:150px;width:500px;overflow:hidden;' }
  = link_to 'Go', edit_level_source_path(level_source_id)

  %div{ style: 'position:absolute;top:0;left:50px' }
    %pre= format_xml(LevelSource.find_by_id(level_source_id).try(:data))

app/views/shared/_student_continue.html.haml
#last
  - script_level = current_user.next_untried_level(Script.twenty_hour_script)
  - if script_level
    #left_off #{t('home.student_left_off')} 
    #{data_t_suffix('script.name', Script.twenty_hour_script.name, script_level.level.game.name)} #{t('puzzle')} #{script_level.game_chapter}
    &nbsp;
    = form_tag(build_script_level_url(script_level), method: 'get', style: "display:inline;") do
      = submit_tag t('continue'), name: nil, class: 'btn btn-primary button-continue', id: 'continue_button'
  - elsif include_finished
    = render partial: 'shared/student_finished', locals: { include_prize_link: true }

app/views/shared/_student_finished.html.haml
= raw t(include_prize_link && current_user.show_prize_ui? ? 'home.student_finished_prize' : 'home.student_finished', prize_link: link_to(t('prize'), my_prizes_url), online_link: link_to(t('home.online'), 'http://code.org/learn/beyond'), local_school_link: link_to(t('home.local_school'), 'http://code.org/learn/local'))

app/views/shared/_student_prize_mini_grid.html.haml
%div{style:"clear:left;"}
- Prize.where(:user_id => nil).group(:prize_provider).count.each do |provider, count|
  - if count > 0
    .prize-item-mini-grid
      %p
        = image_tag(provider.image_name, :class => 'prize-card-mini-img')
%div{style:"clear:left;"}

app/views/shared/_teacher_nav.html.haml
%span{ style: 'color: #ffa400;'}
  = link_to_if current != 'manage', "Manage students", manage_followers_path
|
%span{ style: 'color: #ffa400;'}
  = link_to_if current != 'addstudents', "Add students", new_follower_path
|
%span{ style: 'color: #ffa400;'}
  = link_to_if current != 'report', t('teacher.rollup'), followers_path
|
%span{ style: 'color: #ffa400;'}
  = link_to_if current != 'activity', "Recent class activity", student_usage_path

app/views/shared/_user_header.html.haml
- if current_user
  .transparent_backdrop{style: 'display:none;'}
  .user_menu
    = link_to raw("#{t('nav.user.label', username: h(current_user.username))} &#x25BC;"), '#', onclick: "return handleUserMenuClick();", class: 'user-menu-link'
    %div{ style: 'position:relative;top:3px;'}
      .user_options{style: 'display: none;'}
        - if current_user.teacher?
          = link_to t('nav.user.classroom'), followers_url
          %hr
        = link_to t('nav.user.stats'), root_url
        %br/
        = link_to t('nav.user.settings'), edit_user_registration_url
        %br/
        - if current_user.show_prize_ui?
          = link_to t('nav.user.prizes'), my_prizes_path
          %br/
        = link_to t('nav.user.logout'), destroy_user_session_url
- elsif params[:controller] !~ /^devise/ and not Rails.configuration.minimal_mode

  = link_to(t('nav.user.signin'), new_user_session_url, class: 'button-signin', id: 'signin_button')

app/views/shared/_user_stats.html.haml
- script = @script || Script.twenty_hour_script
- script_levels = user ? user.levels_from_script(Script.twenty_hour_script) : script.script_levels
- concept_progress = user ? user.concept_progress : nil

-if (!defined? trophies_on_right) || !trophies_on_right
  =render partial: 'shared/concept_trophy_block', locals: { concept_progress: concept_progress, user: user, added_style: 'padding-right:10px;' }

%div{style:"display:inline-block;width:315px;position:relative;overflow:hidden;float:left;"}
  %h4 #{t('nav.popup.puzzle_map')}

  - script_levels.group_by{ |sl| sl.level.game }.each_pair do |game, sl_group|
    - title = data_t_suffix('script.name', script.name, game.name) + ' ' + data_t('game.name', game.name)
    .game-group
      - if sl_group.length == 1
        .single-game
          - sl = sl_group.first
          - passed, link = level_info(user, sl)
          %a{href: link, class: ('level-done' if passed)}
            %span=title
            - if passed
              = check_mark_html
      - else
        %div=title
        - sl_group.each do |sl|
          - passed, link = level_info(user, sl)
          - if passed
            %a{ href: link, class: "level_link level_link_done"}
              = check_mark_html
          - else
            %a{ href: link, class: "level_link"}
              #{sl.game_chapter}

    .stage_separator

-if (defined? trophies_on_right) && trophies_on_right
  =render partial: 'shared/concept_trophy_block', locals: { concept_progress: concept_progress, user: user, added_style: 'padding-left:30px;' }

app/views/shared/overloaded.html.haml
%h1 Oh no!

%h2
  Too many people are trying to learn to code all at once and our poor little
  servers can't handle it.

%h3
  We've temporarily disabled our accounts system and some other functionality
  so that we can better serve all of our visitors.

%center
  %br
  %big
    = link_to 'Go to the homepage', root_url
    or
    = link_to 'Visit one of our partners', 'http://code.org/learn/'
  %br
  %br
  %br