config/routes.rb
Dashboard::Application.routes.draw do
  resources :teacher_bonus_prizes
  resources :teacher_prizes
  resources :prizes
  resources :callouts
  resources :videos
  resources :concepts
  resources :activities
  resources :sections, only: [:new, :create, :edit, :update, :destroy]
  resources :level_sources, path: '/sh/', only: [:show, :edit]
  get '/share/:id', to: redirect('/sh/%{id}')
  get '/sh/:id/generate_image', to: 'level_sources#generate_image'

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    sessions: 'sessions'
  }

  post '/signup_check/username', to: 'home#check_username'

  root :to => "home#index"
  get '/home_insert', to: 'home#home_insert'
  get '/health_check', to: 'home#health_check'
  get '/admin/debug', to: 'home#debug'

  post '/locale', to: 'home#set_locale', as: 'locale'

  resources :games do
    resources :levels
  end

  resources :scripts, only: [], path: '/s/' do
    resources :script_levels, as: :levels, only: [:show], path: "/level", format: false do
      get 'solution', to: 'script_levels#solution'
    end
  end

  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID, reset:true, as: 'hoc_reset'
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID, as: 'hoc_chapter', format: false

  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID, as: 'k8intro_chapter', format: false

  resources :prize_providers
  get '/prize_providers/:id/claim_prize', to: 'prize_providers#claim_prize', as: 'prize_provider_claim_prize'

  resources :followers, only: [:new, :create, :index]
  get '/followers/:teacher_user_id/accept', to: 'followers#accept', as: 'follower_accept'
  post '/followers/create_student', to: 'followers#create_student', as: 'create_student'
  get '/followers/manage', to: 'followers#manage', as: 'manage_followers'

  get '/followers/change_password/:user_id', to: 'followers#student_edit_password', as: 'student_edit_password'
  post '/followers/save_password', to: 'followers#student_update_password', as: 'student_update_password'

  post '/followers/add_to_section', to: 'followers#add_to_section', as: 'add_to_section'
  post '/followers/remove_from_section', to: 'followers#remove_from_section', as: 'remove_from_section'
  get '/join(/:section_code)', to: 'followers#student_user_new', as: 'student_user_new'
  post '/join/:section_code', to: 'followers#student_register', as: 'student_register'

  post '/milestone/:user_id/:script_level_id', :to => 'activities#milestone', :as => 'milestone'

  get '/admin/usage', to: 'reports#all_usage', as: 'all_usage'
  get '/admin/stats', to: 'reports#admin_stats', as: 'admin_stats'
  get '/admin/progress', to: 'reports#admin_progress', as: 'admin_progress'
  get '/stats/usage/:user_id', to: 'reports#usage', as: 'usage'
  get '/stats/students', to: 'reports#students', as: 'student_usage'
  get '/stats/:user_id', to: 'reports#user_stats', as: 'user_stats'
  get '/stats/level/:level_id', to: 'reports#level_stats', as: 'level_stats'
  get '/popup/stats', to: 'reports#header_stats', as: 'header_stats'
  get '/redeemprizes', to: 'reports#prizes', as: 'my_prizes'

  get '/notes/:key', to: 'notes#index'

  get '/api/user_menu', to: 'api#user_menu', as: 'user_menu'
  get '/api/user_hero', to: 'api#user_hero', as: 'user_hero'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def set_locale
    cookies[:language_] = params[:locale] if params[:locale]
    redirect_to params[:return_to]
  end

  def check_username
    if !params[:username] || params[:username].length < 5
      render json: { message: I18n.t('signup_form.invalid_username'), available: false }
    else
      if User.exists?(username: params[:username])
        render json: { message: I18n.t('signup_form.taken_username'), available: false }
      else
        render json: { message: I18n.t('signup_form.valid_username'), available: true }
      end
    end
  end

  def home_insert
    if current_user
      render 'index', layout: false, formats: [:html]
    else
      render text: ''
    end
  end

  def health_check
    render text: 'healthy!'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/debug.html.haml
%h1 Debug page

%table{ border: "1" }
  %tr
    %td Params
    %td= params.inspect
  %tr
    %th Cookies
  - cookies.each do |c|
    %tr
      %td= c[0]
      %td= c[1]
  %tr
    %th Request Env
  - request.env.each_pair do |k,v|
    %tr
      %td= k
      %td= v
  %tr
    %td Request
    %td= request.inspect

app/views/home/index.html.haml
- if current_user
  .row
    .span12
      %h1= t('welcome_back', name: current_user.name)
      %hr

      - if current_user.students.length > 0 || current_user.teacher?
        %h4 #{t('home.classroom')}:

        %p
          = link_to t('home.teacher_student_count', count: current_user.students.length), manage_followers_path
          = t('home.teacher_averages', trophy_average: ("%.1f" % current_user.average_student_trophies), trophy_max: Trophy::TROPHY_MAX)

        = render partial: 'shared/teacher_nav', locals: { current: 'home' }
        %hr

      %h4 #{t('home.student_progress')}:
      = t('home.student_stats', trophy_count: current_user.trophy_count, trophy_max: Trophy::TROPHY_MAX)
      %br/

      %div{ style: 'padding-top: 10px; padding-bottom: 10px;'}
        = render partial: 'shared/student_continue', locals: { include_finished: true }
        - if !current_user.teacher? && current_user.teachers.length == 0
          = link_to t('add_teacher_form.submit'), "#" + :teacher_email_or_code.to_s
- else
  %h3= link_to t('try_hoc'), hoc_reset_path()
  = link_to t('already_started'), hoc_chapter_path(ScriptLevel::NEXT)
  %br/
  %br/

  %hr

  %h3= link_to t('try_k8intro'), k8intro_chapter_path(ScriptLevel::NEXT)
  = image_tag 'signup_header.jpg'
  %br/

  - unless Rails.configuration.minimal_mode
    %br/
    %p
      #{t('nav.user.signup')}: #{link_to t('home.student_reg_link'), new_user_registration_path} | #{link_to t('home.teacher_reg_link'), new_user_registration_path('user[user_type]' => User::TYPE_TEACHER)}.
      #{raw t('home.signin_message', link: link_to(t('nav.user.signin'), new_user_session_path))}.


.row
  .span12
    = render partial: 'shared/user_stats', locals: { user: current_user, trophies_on_right: true }

%br/
- if current_user && !current_user.teacher?
  - if current_user.teachers.length > 1
    = t('teacher.title.other')
    = current_user.teachers.map(&:name).join(', ')
  - elsif current_user.teachers.length == 1
    = t('teacher.title.one', name: current_user.teachers.first.name)
  - else
    %h4= t('add_teacher_form.code_or_email.label')
    = form_for([Follower.new]) do |f|
      .field
        = text_field_tag :teacher_email_or_code, nil, class: 'input-xxlarge', placeholder: t('add_teacher_form.code_or_email.placeholder'), :required => true
        = hidden_field_tag :redirect, root_path
      .actions
        = f.submit t('add_teacher_form.submit')
%br/

- if current_user && current_user.admin?
  %h3= t(:demos)
  %ul
    - Script.all.each do |script|
      %li= link_to(data_t_suffix('script.name', script.name, 'desc'), script_level_path(script, ScriptLevel::NEXT))
  %h3= link_to 'Admin Stats', admin_stats_path