config/routes.rb
Dashboard::Application.routes.draw do
  resources :teacher_bonus_prizes
  resources :teacher_prizes
  resources :prizes
  resources :callouts
  resources :videos
  resources :concepts
  resources :activities
  resources :sections, only: [:new, :create, :edit, :update, :destroy]
  resources :level_sources, path: '/sh/', only: [:show, :edit]
  get '/share/:id', to: redirect('/sh/%{id}')
  get '/sh/:id/generate_image', to: 'level_sources#generate_image'

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    sessions: 'sessions'
  }

  post '/signup_check/username', to: 'home#check_username'

  root :to => "home#index"
  get '/home_insert', to: 'home#home_insert'
  get '/health_check', to: 'home#health_check'
  get '/admin/debug', to: 'home#debug'

  post '/locale', to: 'home#set_locale', as: 'locale'

  resources :games do
    resources :levels
  end

  resources :scripts, only: [], path: '/s/' do
    resources :script_levels, as: :levels, only: [:show], path: "/level", format: false do
      get 'solution', to: 'script_levels#solution'
    end
  end

  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID, reset:true, as: 'hoc_reset'
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID, as: 'hoc_chapter', format: false

  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID, as: 'k8intro_chapter', format: false

  resources :prize_providers
  get '/prize_providers/:id/claim_prize', to: 'prize_providers#claim_prize', as: 'prize_provider_claim_prize'

  resources :followers, only: [:new, :create, :index]
  get '/followers/:teacher_user_id/accept', to: 'followers#accept', as: 'follower_accept'
  post '/followers/create_student', to: 'followers#create_student', as: 'create_student'
  get '/followers/manage', to: 'followers#manage', as: 'manage_followers'

  get '/followers/change_password/:user_id', to: 'followers#student_edit_password', as: 'student_edit_password'
  post '/followers/save_password', to: 'followers#student_update_password', as: 'student_update_password'

  post '/followers/add_to_section', to: 'followers#add_to_section', as: 'add_to_section'
  post '/followers/remove_from_section', to: 'followers#remove_from_section', as: 'remove_from_section'
  get '/join(/:section_code)', to: 'followers#student_user_new', as: 'student_user_new'
  post '/join/:section_code', to: 'followers#student_register', as: 'student_register'

  post '/milestone/:user_id/:script_level_id', :to => 'activities#milestone', :as => 'milestone'

  get '/admin/usage', to: 'reports#all_usage', as: 'all_usage'
  get '/admin/stats', to: 'reports#admin_stats', as: 'admin_stats'
  get '/admin/progress', to: 'reports#admin_progress', as: 'admin_progress'
  get '/stats/usage/:user_id', to: 'reports#usage', as: 'usage'
  get '/stats/students', to: 'reports#students', as: 'student_usage'
  get '/stats/:user_id', to: 'reports#user_stats', as: 'user_stats'
  get '/stats/level/:level_id', to: 'reports#level_stats', as: 'level_stats'
  get '/popup/stats', to: 'reports#header_stats', as: 'header_stats'
  get '/redeemprizes', to: 'reports#prizes', as: 'my_prizes'

  get '/notes/:key', to: 'notes#index'

  get '/api/user_menu', to: 'api#user_menu', as: 'user_menu'
  get '/api/user_hero', to: 'api#user_hero', as: 'user_hero'

end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :user
  belongs_to :student_user, foreign_key: "student_user_id", class_name: User
  belongs_to :section
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  PROVIDER_MANUAL = 'manual'

  TYPE_STUDENT = 'student'
  TYPE_TEACHER = 'teacher'
  TYPE_PARENT = 'parent'

  GENDER_OPTIONS = [[nil, ''], ['gender.male', 'm'], ['gender.female', 'f'], ['gender.none', '-']]
  
  STUDENTS_COMPLETED_FOR_PRIZE = 15
  STUDENTS_FEMALE_FOR_BONUS = 7

  attr_accessor :login

  has_many :user_levels
  has_many :sections

  has_many :user_trophies
  has_many :trophies, through: :user_trophies, source: :trophy

  has_many :followers
  has_many :followeds, -> { order 'id'}, :class_name => 'Follower', :foreign_key => 'student_user_id'

  has_many :students, through: :followers, source: :student_user
  has_many :teachers, through: :followeds, source: :user
  
  has_one :prize
  has_one :teacher_prize
  has_one :teacher_bonus_prize

  validates_format_of :email, with: Devise::email_regexp, allow_blank: true, on: :create
  #validates_length_of :first_name, maximum: 35
  #validates_length_of :last_name, maximum: 35
  validates_length_of :name, within: 1..70
  validates_length_of :email, maximum: 255
  # this is redundant to devise, but required for tests?
  validates_uniqueness_of :email, allow_nil: true, allow_blank: true, case_sensitive: false
  validates_length_of :parent_email, maximum: 255
  validates_length_of :username, within: 5..20
  validates_format_of :username, with: /\A[a-z0-9\-\_\.]+\z/i, on: :create
  validates_uniqueness_of :username, allow_nil: false, allow_blank: false, case_sensitive: false
  validates_uniqueness_of :prize_id, allow_nil: true
  validates_uniqueness_of :teacher_prize_id, allow_nil: true
  validates_uniqueness_of :teacher_bonus_prize_id, allow_nil: true

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      user.name = auth.info.name
      user.email = auth.info.email
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && (provider.blank? || (User::PROVIDER_MANUAL == provider))
  end

  def email_required?
    User::PROVIDER_MANUAL != provider
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(['username = :value OR email = :value', { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def levels_from_script(script, game_index=nil)
    ul_map = self.user_levels.includes({level: [:game, :concepts]}).index_by(&:level_id)
    q = script.script_levels.includes({ level: :game }, :script).order(:chapter)

    if game_index
      q = q.where(['games.id = :index', { :index => game_index}]).references(:game)
    end

    q.each do |sl|
      ul = ul_map[sl.level_id]
      sl.user_level = ul
    end
  end

  def next_untried_level(script)
    ScriptLevel.find_by_sql(<<SQL).first
select sl.*
from script_levels sl
left outer join user_levels ul on ul.level_id = sl.level_id and ul.user_id = #{self.id}
    where sl.script_id = #{script.id} and (ul.best_result is null or ul.best_result < #{Activity::MINIMUM_PASS_RESULT})
order by sl.chapter
limit 1
SQL
  end

  def progress(script)
    #trophy_id summing is a little hacky, but efficient. It takes advantage of the fact that:
    #broze id: 1, silver id: 2 and gold id: 3
    self.connection.select_one(<<SQL)
select
  count(case when ul.best_result >= #{Activity::MINIMUM_PASS_RESULT} then 1 else null end) as current_levels,
  count(*) as max_levels,
  (select coalesce(sum(trophy_id), 0) from user_trophies where user_id = #{self.id}) as current_trophies,
  (select count(*) * 3 from concepts) as max_trophies
from script_levels sl
left outer join user_levels ul on ul.level_id = sl.level_id and ul.user_id = #{self.id}
where sl.script_id = #{script.id}
SQL
  end

  def concept_progress(script = Script.twenty_hour_script)
    # todo: cache everything but the user's progress
    user_levels_map = self.user_levels.includes([{level: :concepts}]).index_by(&:level_id)
    user_trophy_map = self.user_trophies.includes(:trophy).index_by(&:concept_id)
    result = Hash.new{|h,k| h[k] = {obj: k, current: 0, max: 0}}

    script.levels.includes(:concepts).each do |level|
      level.concepts.each do |concept|
        result[concept][:current] += 1 if user_levels_map[level.id].try(:best_result).to_i >= Activity::MINIMUM_PASS_RESULT
        result[concept][:max] += 1
        result[concept][:trophy] ||= user_trophy_map[concept.id]
      end
    end
    result
  end

  def last_attempt(level)
    Activity.where(user_id: self.id, level_id: level.id).order('id desc').first
  end

  # returns a map from section to the users in that section
  def students_by_section
    class_map = Hash.new{ |h,k| h[k] = [] }
    self.followers.includes([:section, :student_user]).each do |f|
      class_map[f.section] << f.student_user
    end
    class_map
  end

  def average_student_trophies
    User.connection.select_value(<<SQL)
select coalesce(avg(num), 0)
from (
    select coalesce(sum(trophy_id), 0) as num
    from followers f
    left outer join user_trophies ut on f.student_user_id = ut.user_id
    where f.user_id = #{self.id}
    group by f.student_user_id
    ) trophy_counts
SQL
  end

  # determines and returns teacher_prize, teacher_bonus_prize
  # ** Does not change values on this User object **
  def check_teacher_prize_eligibility
    completed_students = 0
    completed_female_students = 0
    total_students = self.students.length
    if total_students >= STUDENTS_COMPLETED_FOR_PRIZE
      self.students.each do |student|
        if student.prize_earned
          completed_students += 1
          if student.gender == "f"
            completed_female_students += 1
          end
        end
      end
    end
    
    teacher_prize = completed_students >= STUDENTS_COMPLETED_FOR_PRIZE
    teacher_bonus_prize = teacher_prize && (completed_female_students >= STUDENTS_FEMALE_FOR_BONUS)
    return teacher_prize, teacher_bonus_prize
  end

  def trophy_count
    User.connection.select_value(<<SQL)
select coalesce(sum(trophy_id), 0) as num
from user_trophies
where user_id = #{self.id}
SQL
  end

  def student?
    self.user_type == TYPE_STUDENT
  end

  def parent?
    self.user_type == TYPE_PARENT
  end

  def teacher?
    self.user_type == TYPE_TEACHER
  end

  # this method will eventually return a per-user value based on an async process of
  # marking each user in the db after checking their first sign-in IP

  # this method should not be used for displaying or claiming prizes - only used as a quick
  # check to decide whether or not to hide UI elements from the pages
  def show_prize_ui?
    true
  end

  def locale
    read_attribute(:locale).try(:to_sym)
  end

  def writable_by?(other_user)
    return true if other_user == self
    return true if other_user.admin?
    return true if self.email.blank? && self.teachers.include?(other_user)
    false
  end
end

app/helpers/followers_helper.rb
module FollowersHelper
  def build_user_level_message(user, user_level, script_level)
    if user_level
      #TODO: Localize
      return <<TEXT
#{user.name}
#{script_level.level.game.name} ##{script_level.game_chapter}
Best result: #{user_level.best_result}
Attempts: #{user_level.attempts}
Last attempt: #{time_ago_in_words(user_level.updated_at)}
First attempt: #{time_ago_in_words(user_level.created_at)}
TEXT
    else
      return "#{user.name} has not attempted #{script_level.level.game.name} ##{script_level.game_chapter}"
    end
  end

  def build_invite_mailto(section, user)
    "mailto:?subject=#{Rack::Utils.escape_path(t('welcome_email.subject'))}&body=#{Rack::Utils.escape_path(t('welcome_email.body', link: student_user_new_url(section_code: section.code), name: user.name))}"
  end
end

app/views/followers/_new_student_form.html.haml
:javascript
  $(function() {
    $( "#user_birthday" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "-120:+0",
    });
  });

= f.text_field(:name, class: 'input-xlarge', placeholder: "Student's full name (John Smith)")
%br/
= f.text_field(:username, class: 'input-xlarge', placeholder: "Student's username")
%br/
= f.password_field(:password, class: 'input-xlarge', placeholder: "Student's password")
%br/
= f.select(:gender, options_for_select([["Student's gender (optional)", '', {disabled: true, selected: true}], ['Male', 'm'], ['Female', 'f']], :selected => user.gender))
%br/
= f.text_field(:birthday, class: 'input-xlarge', id: "user_birthday", placeholder: "Student's birthday")

%br/
= f.text_field(:parent_email, class: 'input-xlarge', placeholder: "Parent's email", character: 200)
%br/
= submit_tag 'Add student', class: "btn btn-primary"

app/views/followers/accept.html.haml
Allow your teacher (#{@teacher.email}) to have access to your progress on Code.org?
= form_tag(follower_accept_path(@teacher), method: 'GET') do
  = hidden_field_tag(:confirm, true)
  = submit_tag('Yes')

app/views/followers/create_student.html.haml
- if @user.errors.any?
  #error_explanation
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

= form_for(@user, url: { action: :create_student }) do |f|
  = render partial: 'new_student_form', locals: { f: f, user: @user }

app/views/followers/index.html.haml
- @page_title = "#{current_user.name} #{t('teacher.rollup')}"
- stage_map = @all_script_levels.group_by { |sl| sl.level.game }
- hours = (params[:hours] || 1).to_i
- add_section_ui = !current_user.sections.blank?

= render partial: 'shared/teacher_nav', locals: { current: 'report' }

%h1= @page_title

%br/

= form_tag(nil, method: 'GET') do
  - if add_section_ui
    %div{ style: 'float: left; padding-right: 30px;'}
      Section:
      = select_tag('section_id', options_from_collection_for_select(current_user.sections.unshift(Section.new(name: 'All')), :id, :name, params[:section_id]), {onchange:"this.form.submit();", style: "width: 140px; margin:0px;"  })
  %div{ style: 'float: left; padding-right: 30px;'}
    Stage(s) to display:
    = select_tag('game_id', options_for_select(@all_games.unshift(Game.new(name: 'all')).map {|g| [t(g.name), g.id]}, params[:game_id]), {onchange:"this.form.submit();", style: "width: 140px; margin:0px;"  })
  %div
    Show student activity (#{bullet_html}) in the past:
    = select_tag('hours', options_for_select([["1 hour", 1], ["day", 24], ["week", 24 * 7]], selected: params[:hours] || 1), {onchange:"this.form.submit();", style: "width: 100px; margin:0px;" })

%hr/

%table{ width: '100%' }
  %tr
    %td{ style: "vertical-align: middle; font-weight: 500; padding-right: 10px;" } Levels key
    %td
      .report_key.level_aced &nbsp;
    %td.report_key_cell
      Completed, perfect
    %td
      .report_key.level_done &nbsp;
    %td.report_key_cell
      Completed, but using too many blocks
    %td{ style: "text-align: center;" }= bullet_html
    %td Indicates student activity in the last #{hours} #{'hour'.pluralize(hours)}
  %tr
    %td
    %td
      .report_key.level_undone &nbsp;
    %td.report_key_cell
      Tried, but not completed
    %td
      .report_key.level_untried &nbsp;
    %td.report_key_cell
      Not tried yet

%br/

%table
  %tr
    %td{ style: "padding: 0px; vertical-align: top;" }
      %table{ style: "width:250px; table-layout:fixed;"}
        - @section_map.each_pair do |section, students|
          %tr.report_row
            %th{ style: "white-space: nowrap; overflow: hidden; text-overflow:ellipsis;padding-left: 5px;"}= section.try(:name) || "No assigned section"
          - students.each do |student|
            %tr.report_row
              %td.fixed_width_cell= link_to "#{student.name} (#{student.username})", user_stats_path(student)

          - if section
            %tr.report_row
              %td{ style: "padding-left: 5px;"}
                #{section.name} code:
                %b= section.code
          %tr.report_row
    %td{ style: "padding: 0px;" }
      %div{ style:"overflow-x:scroll; width: 800px; margin:0px; padding: 0px;" }
        %table{ style:"width:#{(@all_concepts.length + @all_script_levels.length) * 25}px;table-layout:fixed;"}
          - @all_concepts.each do
            %col{ width: '25px'}
          - @all_script_levels.each do
            %col{ width: '25px'}
          - @section_map.each_pair do |section, students|
            %tr.report_row
              %th{ colspan: @all_concepts.length } Trophies
              - stage_map.each_pair do |game, levels|
                %th{ colspan: levels.length, style: "overflow: hidden;" }= game.name
            - students.each do |student|
              - trophy_map = student.user_trophies.index_by {|ut| ut.concept_id }
              - level_map = student.user_levels.index_by {|ul| ul.level_id }
              %tr.report_row
                - @all_concepts.each do |concept|
                  - ut = trophy_map[concept.id]
                  %td{ class: "report_cell #{"trophy_#{ut.trophy.name.downcase}" if ut}", title: "#{student.name} has won #{ut.try(:trophy) ? "the #{data_t('trophy.name', ut.trophy.name)}" : 'no'} trophy in the '#{concept.name}' concept" }
                    - if ut && (ut.updated_at > hours.hours.ago)
                      = bullet_html

                - @all_script_levels.each do |sl|
                  - ul = level_map[sl.level_id]
                  %td{ class: "report_cell #{level_box_class(ul.try(:best_result))}", title: build_user_level_message(student, ul, sl) }
                    - if ul
                      - if (ul.updated_at > hours.hours.ago)
                        = bullet_html
                      - elsif ul.passing?
                        = check_mark_html
            - if section
              %tr.report_row
            %tr.report_row

app/views/followers/manage.html.haml
- @page_title = "Manage students"
- add_section_ui = !current_user.sections.blank?

= render partial: 'shared/teacher_nav', locals: { current: 'manage' }

%h1= @page_title

%br/

= form_tag(add_to_section_path) do
  - if add_section_ui
    %p
      Assign checked students to section:
      - options_select = options_from_collection_for_select(current_user.sections, :id, :name)
      - options_select += '<option value="NULL">(None)</option'.html_safe
      = select_tag('section_id', options_select, style: 'margin: 0')
      = submit_tag 'Go'

  %fieldset
    %table{ style: "width:750px; table-layout:fixed;"}
      %colgroup
        %col{ width: 50 }
        %col{ width: 250 }
        %col{ width: 100 }
        %col{ width: 375 }

      %tr
        %th= add_section_ui ? check_box_tag(nil, nil, false, class: :checkall) : ''
        %th Name
        %th Password
        %th Section

      - @followers.each do |followed|
        %tr
          %td= add_section_ui ? check_box_tag('follower_ids[]', followed.id) : ''
          %td.fixed_width_cell= link_to followed.student_user.name || followed.student_user.username, user_stats_path(followed.student_user)
          %td= followed.student_user.email.blank? ? link_to("Edit", student_edit_password_path(followed.student_user)) : ''
          %td
            = followed.section.try(:name)
            = link_to("(remove student)", remove_from_section_path(follower_id: followed.student_user_id, section_id: followed.section_id), method: :post) if followed.section.present?

%br/
= link_to 'Add student', new_follower_path
%br/
= link_to 'Add section', new_section_path

:javascript
  $(function () {
      $('.checkall').on('click', function () {
          $(this).closest('fieldset').find(':checkbox').prop('checked', this.checked);
      });
  });

app/views/followers/new.html.haml
- @page_title = "Add students"

= render partial: 'shared/teacher_nav', locals: { current: 'addstudents' }

%h1= @page_title

%br/

%h4 Ask your students to register themselves

%p
  Instead of making you spend a lot of time individually importing student data, you can set up your class quickly
  by asking them to signup. Your students will need to choose usernames and passwords, but they WON'T be required to
  provide an email address. If a student forgets their password, you will be able to reset it for them.
%p
  Ask your students to visit
  %b= link_to 'code.org/join', 'http://code.org/join'
  and enter their section-code:
  %br/
  - if current_user.sections.empty?
    First, please #{link_to 'add a section', new_section_path}
  - else
    - current_user.sections.each do |section|
      For
      %b= section.name
      enter:
      %b= section.code
      = link_to '(Send in email)', build_invite_mailto(section, current_user), target: :_blank
      %br/
    %br/
    = link_to 'Add section', new_section_path

-#%hr
-#
-#%h4 Add students by email
-#%p
-#  = form_for([Follower.new]) do |f|
-#    = text_field_tag(:student_email_or_username, nil, class: 'input-xlarge', placeholder: 'student@school.edu')
-#    %br/
-#    = submit_tag 'Invite student', class: "btn btn-primary"
-#
-#%hr
-#
-#%h4 Create accounts for your students
-#%p
-#  - user = User.new
-#  = form_for(user, url: { action: :create_student }) do |f|
-#    = render partial: 'new_student_form', locals: { f: f, user: user }

app/views/followers/student_edit_password.html.haml
%h1 Change #{@user.name}'s password

= form_for(@user, url: student_update_password_path, method: 'post') do |f|
  = f.hidden_field(:id)
  = f.password_field(:password, class: 'input-xlarge', placeholder: "New password")
  %br/
  = f.password_field(:password_confirmation, class: 'input-xlarge', placeholder: "Re-enter new password")
  %br/
  = submit_tag 'Change password', class: "btn btn-primary"

app/views/followers/student_user_new.html.haml
:javascript
  $(function() {
    $( "#user_birthday" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "-120:+0",
    });
  });

- if !@section
  Please enter the code shared with you by your teacher. It's a 6-character code made up of letters and numbers
  %br/
  = form_tag(student_user_new_path, method: 'GET') do
    = text_field_tag(:section_code, params[:section_code], placeholder: "6-character code (ABCDEF)")
    %br/
    = submit_tag 'Go', class: 'btn btn-primary'
- elsif current_user
  You are currently signed in as #{current_user.username}. #{link_to "Return home", root_path} or #{link_to("log out", destroy_user_session_path)} to proceed.
- else
  %h2 Register to join the class #{@section.name} taught by #{@section.user.name}
  - if @user.errors.any?
    #error_explanation
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  = form_for(@user, url: { action: :student_register }) do |f|

    = f.text_field(:name, placeholder: "Full name (John Smith)")
    %br/
    = f.text_field(:username, placeholder: "Username")
    %br/
    = f.password_field(:password, placeholder: "Password")
    %br/
    = f.select(:gender, options_for_select([["Gender (optional)", '', {disabled: true, selected: true}], ['Male', 'm'], ['Female', 'f']], :selected => @user.gender))
    %br/
    = f.text_field(:birthday, id: "user_birthday", placeholder: "Birthday (optional)")

    %br/
    = submit_tag 'Register', class: 'btn btn-primary'