config/routes.rb
Dashboard::Application.routes.draw do
  resources :teacher_bonus_prizes
  resources :teacher_prizes
  resources :prizes
  resources :callouts
  resources :videos
  resources :concepts
  resources :activities
  resources :sections, only: [:new, :create, :edit, :update, :destroy]
  resources :level_sources, path: '/sh/', only: [:show, :edit]
  get '/share/:id', to: redirect('/sh/%{id}')
  get '/sh/:id/generate_image', to: 'level_sources#generate_image'

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    sessions: 'sessions'
  }

  post '/signup_check/username', to: 'home#check_username'

  root :to => "home#index"
  get '/home_insert', to: 'home#home_insert'
  get '/health_check', to: 'home#health_check'
  get '/admin/debug', to: 'home#debug'

  post '/locale', to: 'home#set_locale', as: 'locale'

  resources :games do
    resources :levels
  end

  resources :scripts, only: [], path: '/s/' do
    resources :script_levels, as: :levels, only: [:show], path: "/level", format: false do
      get 'solution', to: 'script_levels#solution'
    end
  end

  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID, reset:true, as: 'hoc_reset'
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID, as: 'hoc_chapter', format: false

  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID, as: 'k8intro_chapter', format: false

  resources :prize_providers
  get '/prize_providers/:id/claim_prize', to: 'prize_providers#claim_prize', as: 'prize_provider_claim_prize'

  resources :followers, only: [:new, :create, :index]
  get '/followers/:teacher_user_id/accept', to: 'followers#accept', as: 'follower_accept'
  post '/followers/create_student', to: 'followers#create_student', as: 'create_student'
  get '/followers/manage', to: 'followers#manage', as: 'manage_followers'

  get '/followers/change_password/:user_id', to: 'followers#student_edit_password', as: 'student_edit_password'
  post '/followers/save_password', to: 'followers#student_update_password', as: 'student_update_password'

  post '/followers/add_to_section', to: 'followers#add_to_section', as: 'add_to_section'
  post '/followers/remove_from_section', to: 'followers#remove_from_section', as: 'remove_from_section'
  get '/join(/:section_code)', to: 'followers#student_user_new', as: 'student_user_new'
  post '/join/:section_code', to: 'followers#student_register', as: 'student_register'

  post '/milestone/:user_id/:script_level_id', :to => 'activities#milestone', :as => 'milestone'

  get '/admin/usage', to: 'reports#all_usage', as: 'all_usage'
  get '/admin/stats', to: 'reports#admin_stats', as: 'admin_stats'
  get '/admin/progress', to: 'reports#admin_progress', as: 'admin_progress'
  get '/stats/usage/:user_id', to: 'reports#usage', as: 'usage'
  get '/stats/students', to: 'reports#students', as: 'student_usage'
  get '/stats/:user_id', to: 'reports#user_stats', as: 'user_stats'
  get '/stats/level/:level_id', to: 'reports#level_stats', as: 'level_stats'
  get '/popup/stats', to: 'reports#header_stats', as: 'header_stats'
  get '/redeemprizes', to: 'reports#prizes', as: 'my_prizes'

  get '/notes/:key', to: 'notes#index'

  get '/api/user_menu', to: 'api#user_menu', as: 'user_menu'
  get '/api/user_hero', to: 'api#user_hero', as: 'user_hero'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!, except: [:header_stats]
  check_authorization except: [:all_usage, :level_stats, :students, :header_stats, :admin_stats, :admin_progress]

  before_action :set_script

  def user_stats
    @user = User.find_by_id(params[:user_id])
    authorize! :read, @user
    if !@user || !(@user.id == current_user.id || @user.teachers.include?(current_user) || current_user.admin?)
      flash[:alert] = I18n.t('reports.error.access_denied')
      redirect_to root_path
      return
    end

    #@recent_activity = Activity.where(['user_id = ?', user.id]).order('id desc').includes({level: :game}).limit(2)
    @recent_levels = UserLevel.find_by_sql(<<SQL)
select ul.*, sl.game_chapter, l.game_id, sl.chapter, sl.script_id, sl.id as script_level_id
from user_levels ul
inner join script_levels sl on sl.level_id = ul.level_id
inner join levels l on l.id = ul.level_id
where sl.script_id = 1 and ul.user_id = #{@user.id}
order by ul.updated_at desc limit 2
SQL
  end

  def header_stats
    render file: "shared/_user_stats", layout: false, locals: { user: current_user }
  end

  def prizes
    authorize! :read, current_user
  end

  def usage
    # arbitrary way to find admins
    @user = User.find(params[:user_id])
    authorize! :read, @user

    @recent_activities = get_base_usage_activity.where(['user_id = ?', @user.id])
  end

  def all_usage
    raise "unauthorized" if !current_user.admin?

    @recent_activities = get_base_usage_activity
    render 'usage', formats: [:html]
  end

  def admin_stats
    raise "unauthorized" if !current_user.admin?
    
    SeamlessDatabasePool.use_persistent_read_connection do
      @user_count = User.count
      @teacher_count = User.where(:user_type => 'teacher').count
      @student_count = @user_count - @teacher_count
      @users_with_teachers = Follower.distinct.count(:student_user_id)
      @users_with_email = User.where('email <> ""').count
 
      @prizes_redeemed = Prize.where('user_id IS NOT NULL').group(:prize_provider).count
      @prizes_available = Prize.where('user_id IS NULL').group(:prize_provider).count
      
      @student_prizes_earned = User.where(:prize_earned => true).count
      @student_prizes_redeemed = Prize.where('user_id IS NOT NULL').count
      @student_prizes_available = Prize.where('user_id IS NULL').count

      @teacher_prizes_earned = User.where(:teacher_prize_earned => true).count
      @teacher_prizes_redeemed = TeacherPrize.where('user_id IS NOT NULL').count
      @teacher_prizes_available = TeacherPrize.where('user_id IS NULL').count
      
      @teacher_bonus_prizes_earned = User.where(:teacher_bonus_prize_earned => true).count
      @teacher_bonus_prizes_redeemed = TeacherBonusPrize.where('user_id IS NOT NULL').count
      @teacher_bonus_prizes_available = TeacherBonusPrize.where('user_id IS NULL').count
    end
  end

  def admin_progress
    raise "unauthorized" if !current_user.admin?
    
    SeamlessDatabasePool.use_persistent_read_connection do
      @user_count = User.count
      @all_script_levels = Script.twenty_hour_script.script_levels.includes({ level: :game })
 
      @levels_attempted = User.joins(:user_levels).group(:level_id).where('best_result > 0').count
      @levels_passed = User.joins(:user_levels).group(:level_id).where('best_result >= 20').count

      @stage_map = @all_script_levels.group_by { |sl| sl.level.game }
    end
  end

  def students
    @recent_activities = current_user.students.blank? ? [] : get_base_usage_activity.where("user_id in (#{current_user.students.map(&:id).join(',')})")
    render 'usage', formats: [:html]
  end

  def level_stats
    raise "unauthorized" if !current_user.admin?

    @level = Level.find(params[:level_id])

    best_code_map = Hash.new{|h,k| h[k] = [k, 0] }
    passing_code_map = Hash.new{|h,k| h[k] = [k, 0] }
    finished_code_map = Hash.new{|h,k| h[k] = [k, 0] }
    unsuccessful_code_map = Hash.new{|h,k| h[k] = [k, 0] }

    Activity.all.where(['level_id = ?', @level.id]).order('id desc').limit(10000).each do |activity|
      if activity.best?
        best_code_map[activity.level_source_id][1] += 1
      elsif activity.passing?
        passing_code_map[activity.level_source_id][1] += 1
      elsif activity.finished?
        finished_code_map[activity.level_source_id][1] += 1
      else
        unsuccessful_code_map[activity.level_source_id][1] += 1
      end
    end

    @best_code = best_code_map.values.sort_by {|v| -v[1] }
    @passing_code = passing_code_map.values.sort_by {|v| -v[1] }
    @finished_code = finished_code_map.values.sort_by {|v| -v[1] }
    @unsuccessful_code = unsuccessful_code_map.values.sort_by {|v| -v[1] }
  end

  private
  def get_base_usage_activity
    Activity.all.order('id desc').includes([:user, :level_source, {level: :game}]).limit(50)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_script
    @script = Script.find(params[:script_id]) if params[:script_id]
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def bronze_fraction_image_path(completion)
    'bronze_' + [[(completion * 10 / Trophy::BRONZE_THRESHOLD).floor * 10, 100].min, 0].max.to_s + '.png'
  end
  def silver_fraction_image_path(completion)
    'silver_' + [[((completion - Trophy::BRONZE_THRESHOLD) * 10 /
                   (Trophy::SILVER_THRESHOLD - Trophy::BRONZE_THRESHOLD)).floor * 10, 100].min, 0].max.to_s + '.png'
  end
  def gold_fraction_image_path(completion)
    'gold_' + [[((completion - Trophy::SILVER_THRESHOLD) * 10 /
                 (Trophy::GOLD_THRESHOLD - Trophy::SILVER_THRESHOLD)).floor * 10, 100].min, 0].max.to_s + '.png'
  end
  
  def level_passed(params)
    result = 0
    if params[:user]
      result = params[:user_level] ? params[:user_level].best_result : 0
    elsif (session[:progress] && session[:progress][params[:level_id]])
      result = session[:progress][params[:level_id]]
    end
  
    result >= Activity::MINIMUM_PASS_RESULT
  end
end

app/views/reports/_code_groups.html.haml
- if !code_summaries.blank?
  %h4= title
  %table
    %tr
      %th Count
      %th Code
    - code_summaries.each do |result|
      %tr
        %td= result[1]
        %td= render partial: 'shared/solution', locals: { level_source_id: result[0], level: level }

app/views/reports/admin_progress.html.haml
%h1 Admin progress

%table
  %tr
    %td{ style: "padding: 0px; vertical-align: top;" }
      %table{ style: "width:150px; table-layout:fixed;"}
        %tr.report_row
          %th{ style: "white-space: nowrap; overflow: hidden; text-overflow:ellipsis;padding-left: 5px;"}= "Signed In Users"
        %tr.report_row{ class: "report_tall_row"}
          %td.fixed_width_cell
            Levels attempted
        %tr.report_row{ class: "report_tall_row"}
          %td.fixed_width_cell
            Levels passed
        %tr.report_row
    %td{ style: "padding: 0px;" }
      %div{ style:"overflow-x:scroll; width: 800px; margin:0px; padding: 0px;" }
        %table{ style:"width:#{@all_script_levels.length * 35}px;table-layout:fixed;"}
          %col{ width: '35px'}
          %tr.report_row
            - @stage_map.each_pair do |game, levels|
              %th{ colspan: levels.length, style: "overflow: hidden;" }= game.name
          %tr.report_row{ class: "report_tall_row"}
            - @all_script_levels.each do |sl|
              - attempt_pct = @levels_attempted[sl.level_id] * 100 / @user_count

              %td{ class: "report_cell", style: "background-color: hsl(#{attempt_pct}, 100%, 40%);" }
                #{attempt_pct}%
          %tr.report_row{ class: "report_tall_row"}
            - @all_script_levels.each do |sl|
              - passed_pct = @levels_passed[sl.level_id] * 100 / @user_count

              %td{ class: "report_cell", style: "background-color: hsl(#{passed_pct}, 100%, 40%);" }
                #{passed_pct}%
          %tr.report_row


%h3= link_to '<< Back to admin stats', admin_stats_path

app/views/reports/admin_stats.html.haml
%h1 Admin stats

%h3 Users with accounts

%b Total users
#{@user_count}
%br/
%b Students
#{@student_count}
%br/
%b Teachers
#{@teacher_count}
%br/
%b Users linked to a teacher
#{@users_with_teachers} (#{@users_with_teachers * 100 / @user_count}%)
%br/
%b Users with an email address
#{@users_with_email} (#{@users_with_email * 100 / @user_count}%)
%br/
%br/

%h3= link_to 'View Level Progress (slow query) >>', admin_progress_path

%h3 Prizes

%b Total student prizes earned
#{@student_prizes_earned}
%br/
%b Total student prizes redeemed
#{@student_prizes_redeemed}
%br/
- @prizes_redeemed.each do |key, value|
  #{key.name} #{value}
  %br/
%b Student prizes available to be redeemed
#{@student_prizes_available}
%br/
- @prizes_available.each do |key, value|
  #{key.name} #{value}
  %br/
%br/

%b Total teacher prizes earned
#{@teacher_prizes_earned}
%br/
%b Total teacher prizes redeemed
#{@teacher_prizes_redeemed}
%br/
%b Teacher prizes available to be redeemed
#{@teacher_prizes_available}
%br/
%br/

%b Total bonus teacher prizes earned
#{@teacher_bonus_prizes_earned}
%br/
%b Total teacher bonus prizes redeemed
#{@teacher_bonus_prizes_redeemed}
%br/
%b Teacher bonus prizes available to be redeemed
#{@teacher_bonus_prizes_available}
%br/
%br/

app/views/reports/level_stats.html.haml
- @page_title = "#{@level.game.name}/#{@level.level_num} stats"

%h1= @page_title

= render partial: 'code_groups', locals: { title: 'Best code (100)', code_summaries: @best_code, level: @level }
= render partial: 'code_groups', locals: { title: 'Passing code (20-99)', code_summaries: @passing_code, level: @level }
= render partial: 'code_groups', locals: { title: 'Finished code (10-19)', code_summaries: @finished_code, level: @level }
= render partial: 'code_groups', locals: { title: 'Unsuccessful code (<10)', code_summaries: @unsuccessful_code, level: @level }

app/views/reports/prizes.html.haml
- @page_title = t('redeem_prizes.title', name: current_user.name)

%h1= @page_title

%br/
- if current_user.students.length > 0
  %h4 #{t('home.classroom')}:

  %p
    = link_to t('home.teacher_student_count', count: current_user.students.length), manage_followers_path
    = t('home.teacher_averages', trophy_average: ("%.1f" % current_user.average_student_trophies), trophy_max: Trophy::TROPHY_MAX)
    %br/
    %br/

  - if current_user.teacher_prize_earned
    %h4= t('redeem_prizes.msg.teacher.earned', num_trophies: Trophy::TROPHY_MAX)
    - if current_user.teacher_prize
      = render partial: 'shared/redeemed_prize', locals: { prize: current_user.teacher_prize }
    - else
      = t('redeem_prizes.msg.choose_teacher')
      %br/
      %br/
      = render partial: 'shared/choose_prize', locals: { prize_collection: TeacherPrize, prize_type: 'teacher' }
  - else
    %h4= sanitize(t('redeem_prizes.msg.teacher.not_earned_title').html_safe, tags: %w(a), attributes: %w(href target))
    = sanitize(t('redeem_prizes.msg.teacher.not_earned', num_trophies: Trophy::TROPHY_MAX).html_safe, tags: %w(a), attributes: %w(href target))
  %div{style:"clear:left;"}
    %br/

  - if current_user.teacher_prize_earned
    - if current_user.teacher_bonus_prize_earned
      %h4= t('redeem_prizes.msg.teacher.bonus.earned', num_trophies: Trophy::TROPHY_MAX)
      - if current_user.teacher_bonus_prize
        = render partial: 'shared/redeemed_prize', locals: { prize: current_user.teacher_bonus_prize }
      - else
        = t('redeem_prizes.msg.choose_teacher')
        %br/
        %br/
        = render partial: 'shared/choose_prize', locals: { prize_collection: TeacherBonusPrize, prize_type: 'teacher_bonus' }
    - else
      %h4= sanitize(t('redeem_prizes.msg.teacher.bonus.not_earned_title').html_safe, tags: %w(a), attributes: %w(href target))
      = sanitize(t('redeem_prizes.msg.teacher.bonus.not_earned', num_trophies: Trophy::TROPHY_MAX).html_safe, tags: %w(a), attributes: %w(href target))
    %div{style:"clear:left;"}
  %hr/
%h4 #{t('home.student_progress')}:
= t('home.student_stats', trophy_count: current_user.trophy_count, trophy_max: Trophy::TROPHY_MAX)
%br/
%br/

- if current_user.prize_earned
  %h4= t('redeem_prizes.msg.earned')
  - if current_user.prize
    = render partial: 'shared/redeemed_prize', locals: { prize: current_user.prize }
  - else
    = t('redeem_prizes.msg.choose')
    %br/
    %br/
    = render partial: 'shared/choose_prize', locals: { prize_collection: Prize, prize_type: 'student' }
  %div{style:"clear:left;"}
    %br/
    = render partial: 'shared/student_finished', locals: { include_prize_link: false }
- else
  %h4= t('redeem_prizes.msg.not_earned_title')
  = t('redeem_prizes.msg.not_earned', num_trophies: Trophy::TROPHY_MAX)
  %br/
  %br/
  = render partial: 'shared/student_prize_mini_grid'
  %br/
  %br/
  = render partial: 'shared/student_continue', locals: { include_finished: false }

%br/
:javascript
  $(document).ready(function() {
    $('a[data-confirm]').click(function(ev) {
      var href = $(this).attr('href');

      if (!$('#dataConfirmModal').length) {
        $('body').append('<div id="dataConfirmModal" tabindex="-1" class="modal" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="dataConfirmLabel">#{t('redeem_prizes.confirm.title')}</h3></div><div class="modal-body"></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">#{t('redeem_prizes.confirm.no')}</button><a class="btn btn-primary" id="dataConfirmOK">#{t('redeem_prizes.confirm.yes')}</a></div></div>');
      }
      $('#dataConfirmModal').find('.modal-body').html($(this).attr('data-confirm'));
      $('#dataConfirmOK').attr('href', href);
      $('#dataConfirmModal').modal({show:true});
      return false;
    });
  });

app/views/reports/usage.html.haml
- @page_title = 'Recent Activity'
- script = Script.twenty_hour_script
- if 'students' == params[:action]
  = render partial: 'shared/teacher_nav', locals: { current: 'activity' }

%h1= @page_title

%br/

.quiet_links
  - @recent_activities.each do |a|
    - sl = script.find_script_level(a.level_id)
    - next unless sl # skip levels from "edit code" script
    %div{ style: "padding: 4px;"}
      = link_to a.user.name, user_stats_path(a.user)
      - if a.best?
        %span{ style: 'color:green'} finished (#{a.attempt}, #{a.test_result})
      - elsif a.passing?
        %span{ style: 'color:orange'} finished (#{a.attempt}, #{a.test_result})
      - else
        %span{ style: 'color:red'} tried (#{a.attempt}, #{a.test_result})
      #{link_to "#{data_t_suffix('script.name', script.name, sl.level.game.name)}, #{t('puzzle')} #{sl.try(:game_chapter)}", build_script_level_path(sl)}, #{ago(a.created_at)}.
      - if a.level_source
        See #{link_to("#{a.user.name}'s code", edit_level_source_path(a.level_source_id))}

app/views/reports/user_stats.html.haml
%h1 Progress report for #{@user.name}

%h5= t('user_stats.recent_activity')
- @recent_levels.each do |ul|
  = ul.passing? ? t('user_level.completed') : t('user_level.tried')
  #{link_to "#{data_t_suffix('script.name', Script.find(ul.script_id).name, ul.level.game.name)}, #{t('puzzle')} #{ul.game_chapter}", script_level_path(script_id: ul.script_id, id: ul.script_level_id)},
  #{ago(ul.updated_at)}
  %br
=link_to "#{t('user_stats.show_more')}...", usage_path(@user)
%br

= render partial: 'shared/user_stats', locals: { user: @user }

- if current_user && current_user.admin?
  %div{ style: "border: 1px solid red;clear:both"}
    Admin:
    %br
    name: #{@user.name}
    %br
    email: #{@user.email}
    %br
    username: #{@user.username}
    - if @user.birthday
      %br
      birthday: #{@user.birthday}
    - if @user.gender
      %br
      gender: #{@user.gender}
    %br
    teachers: #{raw @user.teachers.map { |t| link_to(t.name, user_stats_path(t)) }.join(', ')}